version: '3.8'
services:
  mongo:
    image: mongo:5.0
    ports:
      - 27018:27017
    container_name: mongo
    hostname: mongo
    command: ['mongod', '--replSet', 'rs0']
    volumes:
      - ./mongo-data:/data/db
      - ./mongo.init.js:/docker-entrypoint-initdb.d/mongo.init.js:ro
    networks:
      - app-network

  gateway:
    build:
      context: .
      dockerfile: docker/Dockerfile.gateway
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - event
    networks:
      - app-network

  auth:
    build:
      context: .
      dockerfile: docker/Dockerfile.auth
    depends_on:
      - mongo
    networks:
      - app-network

  event:
    build:
      context: .
      dockerfile: docker/Dockerfile.event
    depends_on:
      - mongo
    networks:
      - app-network

  mock-reward:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-reward
    networks:
      - app-network

  mock-reward-condition:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-reward-condition
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
