FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm install

COPY apps/mock-reward ./apps/mock-reward

RUN npm run build mock-reward

EXPOSE 3000

CMD ["node", "dist/apps/mock-reward/main.js"]
