FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm install

COPY apps/auth ./apps/auth

RUN npm run build auth

EXPOSE 3000

CMD ["node", "dist/apps/auth/main.js"]
