FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm install

COPY apps/mock-reward-condition ./apps/mock-reward-condition

RUN npm run build mock-reward-condition

EXPOSE 3000

CMD ["node", "dist/apps/mock-reward-condition/main.js"]
