FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY nest-cli.json ./

RUN npm install

COPY apps/event ./apps/event

RUN npm run build event

EXPOSE 3000

CMD ["node", "dist/apps/event/main.js"]
