export enum RewardClaimStatus {
  SUCCESS = 'SUCCESS',
  REQUESTED = 'REQUESTED',
  FAILED = 'FAILED',
}

export enum RewardClaimResultReason {
  EVENT_STATUS = 'EVENT_STATUS',
  DUPLICATED_CLAIM = 'DUPLICATED_CLAIM',
  CONDITION_NOT_MET = 'CONDITION_NOT_MET',
  GRANT_FAILED = 'GRANT_FAILED',
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNKNOWN = 'UNKNOWN',
  NONE = 'NONE',
}
